version: "3.8"
services:

  node-back:
    build: 
      context: .
      dockerfile: build/production.Dockerfile
    image: "node-back"
    user: "root"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGO_CONN=mongodb+srv://agendapp_user:agenda2021@cluster0.eig00.mongodb.net/db_agendapp?authSource=admin&replicaSet=atlas-12hsa1-shard-0&w=majority&readPreference=primary&retryWrites=true&ssl=true
      - JWT_SECRET=GDFFkaouwpoHPOyq87oD724
      - POSTGRES_CONN=postgres://vwhjglxv:wZpa1qXCuRA_tUdrobf7_1jbSCwhlaVa@batyr.db.elephantsql.com/vwhjglxv
    ports:
      - 4000:3000
    